/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ItinerariesRouteImport } from './routes/itineraries'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangAboutRouteImport } from './routes/$lang.about'
import { Route as LangCareersRouteImport } from './routes/$lang.careers'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as LangGalleryRouteImport } from './routes/$lang.gallery'
import { Route as LangItinerariesRouteImport } from './routes/$lang.itineraries'
import { Route as LangOffersRouteImport } from './routes/$lang.offers'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as CabinsIndexRouteImport } from './routes/cabins.index'
import { Route as CabinsCabinIdRouteImport } from './routes/cabins.$cabinId'
import { Route as DevSyncRouteImport } from './routes/dev.sync'
import { Route as ServicesServiceIdRouteImport } from './routes/services.$serviceId'
import { Route as LangCabinsIndexRouteImport } from './routes/$lang.cabins.index'
import { Route as LangCabinsCabinIdRouteImport } from './routes/$lang.cabins.$cabinId'
import { Route as LangServicesServiceIdRouteImport } from './routes/$lang.services.$serviceId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin.applications'
import { Route as AuthenticatedAdminCabinsRouteImport } from './routes/_authenticated/admin.cabins'
import { Route as AuthenticatedAdminItinerariesRouteImport } from './routes/_authenticated/admin.itineraries'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminShipsIndexRouteImport } from './routes/_authenticated/admin.ships.index'
import { Route as AuthenticatedAdminShipsShipIdRouteImport } from './routes/_authenticated/admin.ships.$shipId'
import { Route as AuthenticatedAdminShipsNewRouteImport } from './routes/_authenticated/admin.ships.new'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesRoute = ItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangCareersRoute = LangCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangGalleryRoute = LangGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => LangRoute,
} as any)
const LangItinerariesRoute = LangItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => LangRoute,
} as any)
const LangOffersRoute = LangOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => LangRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinsIndexRoute = CabinsIndexRouteImport.update({
  id: '/cabins/',
  path: '/cabins/',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinsCabinIdRoute = CabinsCabinIdRouteImport.update({
  id: '/cabins/$cabinId',
  path: '/cabins/$cabinId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSyncRoute = DevSyncRouteImport.update({
  id: '/dev/sync',
  path: '/dev/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const LangCabinsIndexRoute = LangCabinsIndexRouteImport.update({
  id: '/cabins/',
  path: '/cabins/',
  getParentRoute: () => LangRoute,
} as any)
const LangCabinsCabinIdRoute = LangCabinsCabinIdRouteImport.update({
  id: '/cabins/$cabinId',
  path: '/cabins/$cabinId',
  getParentRoute: () => LangRoute,
} as any)
const LangServicesServiceIdRoute = LangServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => LangRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCabinsRoute =
  AuthenticatedAdminCabinsRouteImport.update({
    id: '/cabins',
    path: '/cabins',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminItinerariesRoute =
  AuthenticatedAdminItinerariesRouteImport.update({
    id: '/itineraries',
    path: '/itineraries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminShipsIndexRoute =
  AuthenticatedAdminShipsIndexRouteImport.update({
    id: '/ships/',
    path: '/ships/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminShipsShipIdRoute =
  AuthenticatedAdminShipsShipIdRouteImport.update({
    id: '/ships/$shipId',
    path: '/ships/$shipId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminShipsNewRoute =
  AuthenticatedAdminShipsNewRouteImport.update({
    id: '/ships/new',
    path: '/ships/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/itineraries': typeof ItinerariesRoute
  '/offers': typeof OffersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/careers': typeof LangCareersRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/gallery': typeof LangGalleryRoute
  '/$lang/itineraries': typeof LangItinerariesRoute
  '/$lang/offers': typeof LangOffersRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/cabins/$cabinId': typeof CabinsCabinIdRoute
  '/dev/sync': typeof DevSyncRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/$lang/': typeof LangIndexRoute
  '/cabins/': typeof CabinsIndexRoute
  '/$lang/cabins/$cabinId': typeof LangCabinsCabinIdRoute
  '/$lang/services/$serviceId': typeof LangServicesServiceIdRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/cabins': typeof AuthenticatedAdminCabinsRoute
  '/admin/itineraries': typeof AuthenticatedAdminItinerariesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/$lang/cabins/': typeof LangCabinsIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/ships/$shipId': typeof AuthenticatedAdminShipsShipIdRoute
  '/admin/ships/new': typeof AuthenticatedAdminShipsNewRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/admin/ships/': typeof AuthenticatedAdminShipsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/itineraries': typeof ItinerariesRoute
  '/offers': typeof OffersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/careers': typeof LangCareersRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/gallery': typeof LangGalleryRoute
  '/$lang/itineraries': typeof LangItinerariesRoute
  '/$lang/offers': typeof LangOffersRoute
  '/admin/login': typeof AdminLoginRoute
  '/cabins/$cabinId': typeof CabinsCabinIdRoute
  '/dev/sync': typeof DevSyncRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/$lang': typeof LangIndexRoute
  '/cabins': typeof CabinsIndexRoute
  '/$lang/cabins/$cabinId': typeof LangCabinsCabinIdRoute
  '/$lang/services/$serviceId': typeof LangServicesServiceIdRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/cabins': typeof AuthenticatedAdminCabinsRoute
  '/admin/itineraries': typeof AuthenticatedAdminItinerariesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/$lang/cabins': typeof LangCabinsIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/ships/$shipId': typeof AuthenticatedAdminShipsShipIdRoute
  '/admin/ships/new': typeof AuthenticatedAdminShipsNewRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/admin/ships': typeof AuthenticatedAdminShipsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$lang': typeof LangRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/itineraries': typeof ItinerariesRoute
  '/offers': typeof OffersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/careers': typeof LangCareersRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/gallery': typeof LangGalleryRoute
  '/$lang/itineraries': typeof LangItinerariesRoute
  '/$lang/offers': typeof LangOffersRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin_/login': typeof AdminLoginRoute
  '/cabins/$cabinId': typeof CabinsCabinIdRoute
  '/dev/sync': typeof DevSyncRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/$lang/': typeof LangIndexRoute
  '/cabins/': typeof CabinsIndexRoute
  '/$lang/cabins/$cabinId': typeof LangCabinsCabinIdRoute
  '/$lang/services/$serviceId': typeof LangServicesServiceIdRoute
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/_authenticated/admin/cabins': typeof AuthenticatedAdminCabinsRoute
  '/_authenticated/admin/itineraries': typeof AuthenticatedAdminItinerariesRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/$lang/cabins/': typeof LangCabinsIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/ships/$shipId': typeof AuthenticatedAdminShipsShipIdRoute
  '/_authenticated/admin/ships/new': typeof AuthenticatedAdminShipsNewRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/_authenticated/admin/ships/': typeof AuthenticatedAdminShipsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/gallery'
    | '/itineraries'
    | '/offers'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/careers'
    | '/$lang/contact'
    | '/$lang/gallery'
    | '/$lang/itineraries'
    | '/$lang/offers'
    | '/admin'
    | '/admin/login'
    | '/cabins/$cabinId'
    | '/dev/sync'
    | '/services/$serviceId'
    | '/$lang/'
    | '/cabins/'
    | '/$lang/cabins/$cabinId'
    | '/$lang/services/$serviceId'
    | '/admin/applications'
    | '/admin/cabins'
    | '/admin/itineraries'
    | '/admin/media'
    | '/$lang/cabins/'
    | '/admin/'
    | '/admin/ships/$shipId'
    | '/admin/ships/new'
    | '/api/public/media/$'
    | '/admin/ships/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/gallery'
    | '/itineraries'
    | '/offers'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/careers'
    | '/$lang/contact'
    | '/$lang/gallery'
    | '/$lang/itineraries'
    | '/$lang/offers'
    | '/admin/login'
    | '/cabins/$cabinId'
    | '/dev/sync'
    | '/services/$serviceId'
    | '/$lang'
    | '/cabins'
    | '/$lang/cabins/$cabinId'
    | '/$lang/services/$serviceId'
    | '/admin/applications'
    | '/admin/cabins'
    | '/admin/itineraries'
    | '/admin/media'
    | '/$lang/cabins'
    | '/admin'
    | '/admin/ships/$shipId'
    | '/admin/ships/new'
    | '/api/public/media/$'
    | '/admin/ships'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$lang'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/gallery'
    | '/itineraries'
    | '/offers'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/careers'
    | '/$lang/contact'
    | '/$lang/gallery'
    | '/$lang/itineraries'
    | '/$lang/offers'
    | '/_authenticated/admin'
    | '/admin_/login'
    | '/cabins/$cabinId'
    | '/dev/sync'
    | '/services/$serviceId'
    | '/$lang/'
    | '/cabins/'
    | '/$lang/cabins/$cabinId'
    | '/$lang/services/$serviceId'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/cabins'
    | '/_authenticated/admin/itineraries'
    | '/_authenticated/admin/media'
    | '/$lang/cabins/'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/ships/$shipId'
    | '/_authenticated/admin/ships/new'
    | '/api/public/media/$'
    | '/_authenticated/admin/ships/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LangRoute: typeof LangRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ItinerariesRoute: typeof ItinerariesRoute
  OffersRoute: typeof OffersRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CabinsCabinIdRoute: typeof CabinsCabinIdRoute
  DevSyncRoute: typeof DevSyncRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  CabinsIndexRoute: typeof CabinsIndexRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries': {
      id: '/itineraries'
      path: '/itineraries'
      fullPath: '/itineraries'
      preLoaderRoute: typeof ItinerariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/careers': {
      id: '/$lang/careers'
      path: '/careers'
      fullPath: '/$lang/careers'
      preLoaderRoute: typeof LangCareersRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/gallery': {
      id: '/$lang/gallery'
      path: '/gallery'
      fullPath: '/$lang/gallery'
      preLoaderRoute: typeof LangGalleryRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/itineraries': {
      id: '/$lang/itineraries'
      path: '/itineraries'
      fullPath: '/$lang/itineraries'
      preLoaderRoute: typeof LangItinerariesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/offers': {
      id: '/$lang/offers'
      path: '/offers'
      fullPath: '/$lang/offers'
      preLoaderRoute: typeof LangOffersRouteImport
      parentRoute: typeof LangRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabins/': {
      id: '/cabins/'
      path: '/cabins'
      fullPath: '/cabins/'
      preLoaderRoute: typeof CabinsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabins/$cabinId': {
      id: '/cabins/$cabinId'
      path: '/cabins/$cabinId'
      fullPath: '/cabins/$cabinId'
      preLoaderRoute: typeof CabinsCabinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/sync': {
      id: '/dev/sync'
      path: '/dev/sync'
      fullPath: '/dev/sync'
      preLoaderRoute: typeof DevSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/cabins/': {
      id: '/$lang/cabins/'
      path: '/cabins'
      fullPath: '/$lang/cabins/'
      preLoaderRoute: typeof LangCabinsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/cabins/$cabinId': {
      id: '/$lang/cabins/$cabinId'
      path: '/cabins/$cabinId'
      fullPath: '/$lang/cabins/$cabinId'
      preLoaderRoute: typeof LangCabinsCabinIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/services/$serviceId': {
      id: '/$lang/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/$lang/services/$serviceId'
      preLoaderRoute: typeof LangServicesServiceIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cabins': {
      id: '/_authenticated/admin/cabins'
      path: '/cabins'
      fullPath: '/admin/cabins'
      preLoaderRoute: typeof AuthenticatedAdminCabinsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/itineraries': {
      id: '/_authenticated/admin/itineraries'
      path: '/itineraries'
      fullPath: '/admin/itineraries'
      preLoaderRoute: typeof AuthenticatedAdminItinerariesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ships/': {
      id: '/_authenticated/admin/ships/'
      path: '/ships'
      fullPath: '/admin/ships/'
      preLoaderRoute: typeof AuthenticatedAdminShipsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ships/$shipId': {
      id: '/_authenticated/admin/ships/$shipId'
      path: '/ships/$shipId'
      fullPath: '/admin/ships/$shipId'
      preLoaderRoute: typeof AuthenticatedAdminShipsShipIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ships/new': {
      id: '/_authenticated/admin/ships/new'
      path: '/ships/new'
      fullPath: '/admin/ships/new'
      preLoaderRoute: typeof AuthenticatedAdminShipsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminCabinsRoute: typeof AuthenticatedAdminCabinsRoute
  AuthenticatedAdminItinerariesRoute: typeof AuthenticatedAdminItinerariesRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminShipsShipIdRoute: typeof AuthenticatedAdminShipsShipIdRoute
  AuthenticatedAdminShipsNewRoute: typeof AuthenticatedAdminShipsNewRoute
  AuthenticatedAdminShipsIndexRoute: typeof AuthenticatedAdminShipsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
  AuthenticatedAdminCabinsRoute: AuthenticatedAdminCabinsRoute,
  AuthenticatedAdminItinerariesRoute: AuthenticatedAdminItinerariesRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminShipsShipIdRoute: AuthenticatedAdminShipsShipIdRoute,
  AuthenticatedAdminShipsNewRoute: AuthenticatedAdminShipsNewRoute,
  AuthenticatedAdminShipsIndexRoute: AuthenticatedAdminShipsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangCareersRoute: typeof LangCareersRoute
  LangContactRoute: typeof LangContactRoute
  LangGalleryRoute: typeof LangGalleryRoute
  LangItinerariesRoute: typeof LangItinerariesRoute
  LangOffersRoute: typeof LangOffersRoute
  LangIndexRoute: typeof LangIndexRoute
  LangCabinsCabinIdRoute: typeof LangCabinsCabinIdRoute
  LangServicesServiceIdRoute: typeof LangServicesServiceIdRoute
  LangCabinsIndexRoute: typeof LangCabinsIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangCareersRoute: LangCareersRoute,
  LangContactRoute: LangContactRoute,
  LangGalleryRoute: LangGalleryRoute,
  LangItinerariesRoute: LangItinerariesRoute,
  LangOffersRoute: LangOffersRoute,
  LangIndexRoute: LangIndexRoute,
  LangCabinsCabinIdRoute: LangCabinsCabinIdRoute,
  LangServicesServiceIdRoute: LangServicesServiceIdRoute,
  LangCabinsIndexRoute: LangCabinsIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LangRoute: LangRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ItinerariesRoute: ItinerariesRoute,
  OffersRoute: OffersRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  CabinsCabinIdRoute: CabinsCabinIdRoute,
  DevSyncRoute: DevSyncRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  CabinsIndexRoute: CabinsIndexRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
